-- MySQL Script generated by MySQL Workbench
-- Mon Jun 14 22:22:00 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema enjoy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema enjoy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `enjoy` DEFAULT CHARACTER SET utf8 ;
USE `enjoy` ;

-- -----------------------------------------------------
-- Table `enjoy`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enjoy`.`usuario` (
  `codusu` INT NOT NULL AUTO_INCREMENT,
  `emausu` VARCHAR(45) NOT NULL,
  `nomusu` VARCHAR(45) NOT NULL,
  `pasusu` VARCHAR(100) NOT NULL,
  `stausu` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`codusu`, `emausu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `enjoy`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enjoy`.`post` (
  `codpos` INT NOT NULL AUTO_INCREMENT,
  `nomaut` VARCHAR(100) NULL,
  `despos` VARCHAR(100) NOT NULL,
  `datvia` DATE NULL,
  `ponpos` TEXT NULL,
  `ponneg` TEXT NULL,
  `ovevia` TEXT NOT NULL,
  `insaut` VARCHAR(45) NULL,
  `autcom` CHAR(1) NOT NULL,
  `camimg1` VARCHAR(100) NULL,
  `camimg2` VARCHAR(100) NULL,
  `camimg3` VARCHAR(100) NULL,
  `datpos` DATE NOT NULL,
  `stapos` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`codpos`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
